#ifndef REST_CPP_HTTP_H
#define REST_CPP_HTTP_H

#include <string>
#include <map>

namespace REST {
namespace HTTP {
namespace STATUS {
  enum Code {
    Continue=100,
    SwitchingProtocols=101,
    Processing=102,
    OK=200,
    Created=201,
    Accepted=202,
    NonAuthoritativeInformation=203,
    NoContent=204,
    ResetContent=205,
    PartialContent=206,
    MultiStatus=207,
    AlreadyReported=208,
    IMUsed=226,
    MultipleChoices=300,
    MovedPermanently=301,
    Found=302,
    SeeOther=303,
    NotModified=304,
    UseProxy=305,
    TemporaryRedirect=307,
    PermanentRedirect=308,
    BadRequest=400,
    Unauthorized=401,
    PaymentRequired=402,
    Forbidden=403,
    NotFound=404,
    MethodNotAllowed=405,
    NotAcceptable=406,
    ProxyAuthenticationRequired=407,
    RequestTimeout=408,
    Conflict=409,
    Gone=410,
    LengthRequired=411,
    PreconditionFailed=412,
    RequestEntityTooLarge=413,
    RequestURITooLong=414,
    UnsupportedMediaType=415,
    RequestedRangeNotSatisfiable=416,
    ExpectationFailed=417,
    ImATeapot=418,
    EnhanceYourCalm=420,
    UnprocessableEntity=422,
    Locked=423,
    FailedDependency=424,
    UpgradeRequired=426,
    PreconditionRequired=428,
    TooManyRequests=429,
    RequestHeaderFieldsTooLarge=431,
    NoResponse=444,
    RetryWith=449,
    ClientClosedRequest=499,
    InternalServerError=500,
    NotImplemented=501,
    BadGateway=502,
    ServiceUnavailable=503,
    GatewayTimeout=504,
    HTTPVersionNotSupported=505,
    VariantAlsoNegotiates=506,
    InsufficientStorage=507,
    LoopDetected=508,
    BandwidthLimitExceeded=509,
    NotExtended=510,
    NetworkAuthenticationRequired=511,
    NetworkReadTimeoutError=598,
    NetworkConnectTimeoutError=599
  };
  
  const static std::map<Code, std::string> messages {
    {(Code) 100, "Continue"},
    {(Code) 101, "Switching Protocols"},
    {(Code) 102, "Processing (WebDAV)"},
    {(Code) 200, "OK"},
    {(Code) 201, "Created"},
    {(Code) 202, "Accepted"},
    {(Code) 203, "Non-Authoritative Information"},
    {(Code) 204, "No Content"},
    {(Code) 205, "Reset Content"},
    {(Code) 206, "Partial Content"},
    {(Code) 207, "Multi-Status (WebDAV)"},
    {(Code) 208, "Already Reported (WebDAV)"},
    {(Code) 226, "IM Used"},
    {(Code) 300, "Multiple Choices"},
    {(Code) 301, "Moved Permanently"},
    {(Code) 302, "Found"},
    {(Code) 303, "See Other"},
    {(Code) 304, "Not Modified"},
    {(Code) 305, "Use Proxy"},
    {(Code) 307, "Temporary Redirect"},
    {(Code) 308, "Permanent Redirect (experiemental)"},
    {(Code) 400, "Bad Request"},
    {(Code) 401, "Unauthorized"},
    {(Code) 402, "Payment Required"},
    {(Code) 403, "Forbidden"},
    {(Code) 404, "Not Found"},
    {(Code) 405, "Method Not Allowed"},
    {(Code) 406, "Not Acceptable"},
    {(Code) 407, "Proxy Authentication Required"},
    {(Code) 408, "Request Timeout"},
    {(Code) 409, "Conflict"},
    {(Code) 410, "Gone"},
    {(Code) 411, "Length Required"},
    {(Code) 412, "Precondition Failed"},
    {(Code) 413, "Request Entity Too Large"},
    {(Code) 414, "Request-URI Too Long"},
    {(Code) 415, "Unsupported Media Type"},
    {(Code) 416, "Requested Range Not Satisfiable"},
    {(Code) 417, "Expectation Failed"},
    {(Code) 418, "I'm a teapot (RFC 2324)"},
    {(Code) 420, "Enhance Your Calm (Twitter)"},
    {(Code) 422, "Unprocessable Entity (WebDAV)"},
    {(Code) 423, "Locked (WebDAV)"},
    {(Code) 424, "Failed Dependency (WebDAV)"},
    {(Code) 426, "Upgrade Required"},
    {(Code) 428, "Precondition Required"},
    {(Code) 429, "Too Many Requests"},
    {(Code) 431, "Request Header Fields Too Large"},
    {(Code) 444, "No Response (Nginx)"},
    {(Code) 449, "Retry With (Microsoft)"},
    {(Code) 499, "Client Closed Request (Nginx)"},
    {(Code) 500, "Internal Server Error"},
    {(Code) 501, "Not Implemented"},
    {(Code) 502, "Bad Gateway"},
    {(Code) 503, "Service Unavailable"},
    {(Code) 504, "Gateway Timeout"},
    {(Code) 505, "HTTP Version Not Supported"},
    {(Code) 506, "Variant Also Negotiates (Experimental)"},
    {(Code) 507, "Insufficient Storage (WebDAV)"},
    {(Code) 508, "Loop Detected (WebDAV)"},
    {(Code) 509, "Bandwidth Limit Exceeded (Apache)"},
    {(Code) 510, "Not Extended"},
    {(Code) 511, "Network Authentication Required"},
    {(Code) 598, "Network read timeout error"},
    {(Code) 599, "Network connect timeout error"}
  };
}
}
}

#endif
